image: docker:stable

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  only:
    - main
    - stage
    - develop
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

Deploy_Dev:
  stage: deploy
  variables:
    BACK_DEV_VERSION: dev_latest
  only:
    - develop
  trigger: team-challenge/e-com/e-com-deployment
  strategy: depend


Deploy_Stage:
  stage: deploy
  variables:
    BACK_STAGE_VERSION: stage_latest
  only:
    - stage
  trigger: team-challenge/e-com/e-com-deployment
  strategy: depend


Deploy_Main:
  stage: deploy
  variables:
    BACK_MAIN_VERSION: main_latest
  only:
    - main
  trigger: team-challenge/e-com/e-com-deployment
  strategy: depend

