version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c  "
      python manage.py wait_for_db &&
      python manage.py migrate && 
      python manage.py collectstatic --noinput &&
      gunicorn online_store.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    env_file:
      - .env

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

